version: "3"
services:
  web:
    image: nginx:latest
    volumes:
     - ./html:/usr/share/nginx/html
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./server1.crt:/etc/nginx/server1.crt
     - ./server1.key:/etc/nginx/server1.key
     - ./server2.crt:/etc/nginx/server2.crt
     - ./server2.key:/etc/nginx/server2.key
     - ./server3.crt:/etc/nginx/server3.crt
     - ./server3.key:/etc/nginx/server3.key
    ports:
     - "80:80"
     - "443:443"
